# -*- coding: utf-8 -*-
"""Finalplant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RuCOA5S6wJ1AR5n8-ouzGY4QawXzHjkj
"""

# STEP 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# STEP 2: Import required libraries
import numpy as np
import json
import tensorflow as tf
from tensorflow.keras.utils import load_img, img_to_array
import matplotlib.pyplot as plt
from pathlib import Path

# STEP 3: Define paths (replace with your actual folder structure if different)
folder_path = Path('/content/drive/MyDrive/Plant detection ML')
model_path = folder_path / 'plant_disease_recog_model_pwp.keras'
json_path = folder_path / 'plant_disease.json'

# STEP 4: Load model and JSON data
model = tf.keras.models.load_model(str(model_path))
with open(json_path, 'r') as file:
    plant_disease = json.load(file)

# STEP 5: Image Upload Helper
from google.colab import files
uploaded = files.upload()

# STEP 6: Feature Extraction Function
def extract_features(image_path):
    image = load_img(image_path, target_size=(160, 160))
    feature = img_to_array(image)
    feature = np.expand_dims(feature, axis=0)
    return feature

# STEP 7: Prediction Function
def model_predict(image_path):
    img = extract_features(image_path)
    prediction = model.predict(img)
    predicted_index = np.argmax(prediction)
    return plant_disease[predicted_index]

# STEP 8: Predict on Uploaded Image
import os

uploaded_filename = next(iter(uploaded))
result = model_predict(uploaded_filename)

# STEP 9: Display Result
print("Prediction:")
print("Disease Name:", result['name'])
print("Cause:", result['cause'])
print("Cure:", result['cure'])

# Optional: Show image
img = load_img(uploaded_filename)
plt.imshow(img)
plt.title(result['name'])
plt.axis('off')
plt.show()